name: LeaderboardPlugin
version: '${project.version}'
main: dev.goldenedit.leaderboardplugin.LeaderboardPlugin
api-version: '1.20'
depend:
  - PlaceholderAPI
commands:
  killcount:
    description: Shows the killcount of a player
    usage: /killcount <player>
    aliases: [kc]
    permission: leaderboardplugin.killcount
  killboard:
    description: Shows the killboard
    usage: /killboard
    aliases: [kb]
    permission: leaderboardplugin.killboard
  calcpoints:
    description: Calculates the points of a player
    usage: /calcpoints <player>
    permission: leaderboardplugin.calcpoints