name: LeaderboardPlugin
version: '${project.version}'
main: dev.goldenedit.leaderboardplugin.LeaderboardPlugin
api-version: '1.20'
depend:
  - PlaceholderAPI
commands:
  points:
    description: Shows the points of a player
    usage: /points <player>
    permission: leaderboardplugin.points
  killboard:
    description: Shows the killboard
    usage: /killboard
    aliases: [kb]
    permission: leaderboardplugin.killboard
  calcpoints:
    description: Calculates the points of a player
    usage: /calcpoints <player>
    permission: leaderboardplugin.calcpoints